AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Exclude:
    - test/dummy_sprockets/**/*
    - test/dummy_webpacker2/**/*
    - test/dummy_webpacker3/**/*
    - node_modules/**/*
    - react_ujs/**/*